import { TBillFormContent } from '@/models';

const tableConf: TBillFormContent | undefined = {
  action: 1,
  billFormType: 'Combination',
  componentModuleName: '系统模块',
  componentName: '系统用户聚合',
  displayName: '系统用户聚合',
  idBillForm: 'CvEdCh9iLCoF2d02iGusJ',
  idComponent: 'Pas2c1HNcmlmPW0HWB4uO',
  idComponentModule: '-IKcXCfnf_Gc2HSZEgs2v',
  idProject: 'hLlXlmUNOcjAaDoWxZzrN',
  idSubProject: 'tuz4_94BGuVuxYxxL6a_r',
  name: 'userAgg',
  projectName: 'Jpa基础项目',
  subProjectName: '系统模型',
  configList: {
    idBillForm: 'VYP2mtmTMqdyYVSVymdlp',
    name: 'newBill',
    displayName: '新表单',
    header: [
      {
        idBillFormTab: 'ATCM0aprTFSxV68Qilg-k',
        entityTypeName: 'User',
        tabCode: 'user',
        firstUpperTabCode: 'User',
        tabName: '系统用户',
        metadataAttrName: 'opkqC1qrs65ADrn7pOmBV',
        tabClassName: 'User',
        firstLowerTabClassName: 'user',
        tabAttrName: 'user',
        firstUpperTabAttrName: 'User',
        billFormFields: [
          {
            idBillFormField: 'KihDUIk2Mp7_ciYKii5bU',
            name: 'idUser',
            dataType: 'PK',
            displayName: '系统用户id',
            fgMainProperty: true,
            showOrder: 0,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '系统用户id',
          },
          {
            idBillFormField: 'ICrTc7DmNA279aI0YLh0z',
            name: 'account',
            dataType: 'String',
            displayName: '登录账号 ',
            fgMainProperty: false,
            showOrder: 1,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '登录账号 ',
          },
          {
            idBillFormField: 'f-I9R_1VrPH1RqxHt7bUd',
            name: 'userPwd',
            dataType: 'String',
            displayName: '用户密码 ',
            fgMainProperty: false,
            showOrder: 2,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '用户密码 ',
          },
          {
            idBillFormField: 'QO_s0rvqbb4jEu8CXrf_M',
            name: 'phone',
            dataType: 'String',
            displayName: '手机号码',
            fgMainProperty: false,
            showOrder: 3,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '手机号码',
          },
          {
            idBillFormField: 'U8JYNAxetslrSvq2-Ai8E',
            name: 'email',
            dataType: 'String',
            displayName: '邮箱',
            fgMainProperty: false,
            showOrder: 4,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '邮箱',
          },
          {
            idBillFormField: 'JNGHqbrifPOIzAMBbwj3u',
            name: 'name',
            dataType: 'String',
            displayName: '姓名 ',
            fgMainProperty: false,
            showOrder: 5,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '姓名 ',
          },
          {
            idBillFormField: 'dEiSlwTxsN6pEId6EWD7b',
            name: 'nickName',
            dataType: 'String',
            displayName: '昵称',
            fgMainProperty: false,
            showOrder: 6,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '昵称',
          },
          {
            idBillFormField: '7X31nQ59rvCmY3nGbEoEH',
            name: 'gender',
            dataType: 'String',
            displayName: '性别',
            fgMainProperty: false,
            showOrder: 7,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Select',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '性别',
            enumConfig: {
              idEnumRef: '4IMEyfTdKpM8KnnuNMCtc',
              enumColumns: [
                {
                  idEnumColumn: 'zRvI1FeVs5OhYIkaQ5Wjh',
                  code: 'UNKNOWN',
                  displayName: '未知',
                  enumValue: 'unknown',
                },
                {
                  idEnumColumn: 'WPhg2FaQViQjGTh1kBJTx',
                  code: 'FEMALE',
                  displayName: '女',
                  enumValue: 'female',
                },
                {
                  idEnumColumn: 'JIh9-fzQf8ksNoluHyJ0D',
                  code: 'MALE',
                  displayName: '男',
                  enumValue: 'male',
                },
              ],
              label: '性别',
              propertyName: 'gender',
              title: '性别',
            },
          },
          {
            idBillFormField: '5KDc89AGipC_EsKoxy_xn',
            name: 'fgActive',
            dataType: 'Boolean',
            displayName: '启用标志',
            fgMainProperty: false,
            showOrder: 8,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Checkbox',
            typeScriptType: 'boolean',
            width: 150,
            textLen: 140,
            placeholder: '启用标志',
            defaultValue: 'true',
          },
        ],
        refType: 'Array',
        orderInfoList: [
          {
            idOrderInfo: 'BLF-44v0Kl5anQseKGDLR',
            orderProperty: 'idUser',
            orderType: 'ASC',
          },
        ],
        fgDefaultTab: true,
        mainProperty: 'idUser',
        tabIndex: 0,
      },
    ],
    body: [
      {
        idAttribute: '93biUvpZmDpjTV4Mc5lRg',
        tabClassName: 'UserRole',
        firstLowerTabClassName: 'userRole',
        tabAttrName: 'userRoles',
        firstUpperTabAttrName: 'UserRoles',
        mainProperty: 'idUserRole',
        refType: 'Array',
        tabCode: 'userRoles',
        firstUpperTabCode: 'UserRoles',
        tabName: '用户角色',
        billFormFields: [
          {
            idBillFormField: 'NQzRqt7mQYYAGHAqRr9Xy',
            name: 'idUserRole',
            displayName: '用户角色关系主属性',
            fgMainProperty: true,
            showOrder: 0,
            readonly: false,
            dataType: 'PK',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '用户角色关系主属性',
          },
          {
            idBillFormField: '0hCeFcYaFtB1d_nRnEm9r',
            name: 'idRole',
            dataType: 'InternalRef',
            displayName: '角色',
            fgMainProperty: false,
            showOrder: 1,
            refAttributeName: 'role',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '角色',
              displayProp: 'displayName',
              backWriteProp: 'idRole',
              tableRef: {
                dataUri: '/role/aqPage',
                tableMainProp: 'idRole',
                ceDisplayName: '角色',
                refColumns: [
                  {
                    idBillRefColumn: 'UgS7AHhML8VQH3_d-JlVm',
                    name: 'name',
                    displayName: '名称',
                  },
                  {
                    idBillRefColumn: '5Z_EWgG4bPupLF0t67c6e',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                ],
              },
            },
            fgDisplay: true,
            width: 150,
            textLen: 140,
          },
        ],
        idBillFormTab: 'oUHFUKN6tTLIV2fBpUpHf',
        tabIndex: 0,
        metadataAttrName: 'userRoles',
        fgDefaultTab: true,
        orderInfoList: [
          {
            idOrderInfo: 'yie0NBDapwmg2gVf2hLz9',
            orderProperty: 'idUserRole',
            orderType: 'ASC',
          },
        ],
      },
    ],
    tail: [],
    mainClass: 'User',
    mainProperty: 'idUser',
    uriConf: {
      page: '/userAgg/aqPage',
      fetchById: '/userAgg/getById',
      batchRemove: '/userAgg/batchRemove',
    },
  },
  configForm: {
    idBillForm: 'VYP2mtmTMqdyYVSVymdlp',
    name: 'newBill',
    displayName: '新表单',
    header: [
      {
        idBillFormTab: 'ATCM0aprTFSxV68Qilg-k',
        entityTypeName: 'User',
        tabCode: 'user',
        firstUpperTabCode: 'User',
        tabName: '系统用户',
        metadataAttrName: 'opkqC1qrs65ADrn7pOmBV',
        tabClassName: 'User',
        firstLowerTabClassName: 'user',
        tabAttrName: 'user',
        firstUpperTabAttrName: 'User',
        billFormFields: [
          {
            idBillFormField: 'KihDUIk2Mp7_ciYKii5bU',
            name: 'idUser',
            dataType: 'PK',
            displayName: '系统用户id',
            fgMainProperty: true,
            showOrder: 0,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '系统用户id',
          },
          {
            idBillFormField: 'ICrTc7DmNA279aI0YLh0z',
            name: 'account',
            dataType: 'String',
            displayName: '登录账号 ',
            fgMainProperty: false,
            showOrder: 1,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '登录账号 ',
          },
          {
            idBillFormField: 'f-I9R_1VrPH1RqxHt7bUd',
            name: 'userPwd',
            dataType: 'String',
            displayName: '用户密码 ',
            fgMainProperty: false,
            showOrder: 2,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '用户密码 ',
          },
          {
            idBillFormField: 'QO_s0rvqbb4jEu8CXrf_M',
            name: 'phone',
            dataType: 'String',
            displayName: '手机号码',
            fgMainProperty: false,
            showOrder: 3,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '手机号码',
          },
          {
            idBillFormField: 'U8JYNAxetslrSvq2-Ai8E',
            name: 'email',
            dataType: 'String',
            displayName: '邮箱',
            fgMainProperty: false,
            showOrder: 4,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '邮箱',
          },
          {
            idBillFormField: 'JNGHqbrifPOIzAMBbwj3u',
            name: 'name',
            dataType: 'String',
            displayName: '姓名 ',
            fgMainProperty: false,
            showOrder: 5,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '姓名 ',
          },
          {
            idBillFormField: 'dEiSlwTxsN6pEId6EWD7b',
            name: 'nickName',
            dataType: 'String',
            displayName: '昵称',
            fgMainProperty: false,
            showOrder: 6,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '昵称',
          },
          {
            idBillFormField: '7X31nQ59rvCmY3nGbEoEH',
            name: 'gender',
            dataType: 'String',
            displayName: '性别',
            fgMainProperty: false,
            showOrder: 7,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Select',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '性别',
            enumConfig: {
              idEnumRef: '4IMEyfTdKpM8KnnuNMCtc',
              enumColumns: [
                {
                  idEnumColumn: 'zRvI1FeVs5OhYIkaQ5Wjh',
                  code: 'UNKNOWN',
                  displayName: '未知',
                  enumValue: 'unknown',
                },
                {
                  idEnumColumn: 'WPhg2FaQViQjGTh1kBJTx',
                  code: 'FEMALE',
                  displayName: '女',
                  enumValue: 'female',
                },
                {
                  idEnumColumn: 'JIh9-fzQf8ksNoluHyJ0D',
                  code: 'MALE',
                  displayName: '男',
                  enumValue: 'male',
                },
              ],
              label: '性别',
              propertyName: 'gender',
              title: '性别',
            },
          },
          {
            idBillFormField: '5KDc89AGipC_EsKoxy_xn',
            name: 'fgActive',
            dataType: 'Boolean',
            displayName: '启用标志',
            fgMainProperty: false,
            showOrder: 8,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Checkbox',
            typeScriptType: 'boolean',
            width: 150,
            textLen: 140,
            placeholder: '启用标志',
            defaultValue: 'true',
          },
        ],
        refType: 'Array',
        orderInfoList: [
          {
            idOrderInfo: 'BLF-44v0Kl5anQseKGDLR',
            orderProperty: 'idUser',
            orderType: 'ASC',
          },
        ],
        fgDefaultTab: true,
        mainProperty: 'idUser',
        tabIndex: 0,
      },
    ],
    body: [
      {
        idAttribute: '93biUvpZmDpjTV4Mc5lRg',
        tabClassName: 'UserRole',
        firstLowerTabClassName: 'userRole',
        tabAttrName: 'userRoles',
        firstUpperTabAttrName: 'UserRoles',
        mainProperty: 'idUserRole',
        refType: 'Array',
        tabCode: 'userRoles',
        firstUpperTabCode: 'UserRoles',
        tabName: '用户角色',
        billFormFields: [
          {
            idBillFormField: 'NQzRqt7mQYYAGHAqRr9Xy',
            name: 'idUserRole',
            displayName: '用户角色关系主属性',
            fgMainProperty: true,
            showOrder: 0,
            readonly: false,
            dataType: 'PK',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '用户角色关系主属性',
          },
          {
            idBillFormField: '0hCeFcYaFtB1d_nRnEm9r',
            name: 'idRole',
            dataType: 'InternalRef',
            displayName: '角色',
            fgMainProperty: false,
            showOrder: 1,
            refAttributeName: 'role',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '角色',
              displayProp: 'displayName',
              backWriteProp: 'idRole',
              tableRef: {
                dataUri: '/role/aqPage',
                tableMainProp: 'idRole',
                ceDisplayName: '角色',
                refColumns: [
                  {
                    idBillRefColumn: 'UgS7AHhML8VQH3_d-JlVm',
                    name: 'name',
                    displayName: '名称',
                  },
                  {
                    idBillRefColumn: '5Z_EWgG4bPupLF0t67c6e',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                ],
              },
            },
            fgDisplay: true,
            width: 150,
            textLen: 140,
          },
        ],
        idBillFormTab: 'oUHFUKN6tTLIV2fBpUpHf',
        tabIndex: 0,
        metadataAttrName: 'userRoles',
        fgDefaultTab: true,
        orderInfoList: [
          {
            idOrderInfo: 'yie0NBDapwmg2gVf2hLz9',
            orderProperty: 'idUserRole',
            orderType: 'ASC',
          },
        ],
      },
    ],
    tail: [],
    mainClass: 'User',
    mainProperty: 'idUser',
    uriConf: {
      fetchById: '/userAgg/getById',
      save: '/userAgg/save',
      update: '/userAgg/save',
      dataRemove: '/userAgg/remove',
    },
  },
};

export { tableConf };
