import { TUiFactoryContent } from '@/models';

const layoutConf: TUiFactoryContent = {
  action: 1,
  componentModuleName: '系统模块',
  componentName: null,
  displayName: '系统菜单',
  fgTemplate: false,
  idComponent: 'hGMwK2ytF8GfF4kFrvSv2',
  idComponentModule: '-IKcXCfnf_Gc2HSZEgs2v',
  idFactory: 'CoxstkfCTAEVAuZ_f-IUB',
  idProject: 'hLlXlmUNOcjAaDoWxZzrN',
  idSubProject: 'tuz4_94BGuVuxYxxL6a_r',
  name: 'Menu',
  projectName: 'Jpa基础项目',
  refIdContent:
    '{"idEditBillform":"kq6Col5Iw9c5l9jDMPy6G","idTree":"RLInQtX7-sNKfYM4NMhEY","idEditButtonAction":"soih4b5Q3f4AogRS_pvA_"}',
  subProjectName: '系统模型',
  modelType: {
    mainType: {
      id: 'p-0GdjOZLYJqX9BgnkX5u',
      className: 'TMenu',
      displayName: '系统菜单',
      attributes: [
        {
          id: '0dDxPn5zTDlfusPIKLSJk',
          attributeName: 'idMenu',
          displayName: '系统菜单id',
          attributeType: 'string',
          fgPk: true,
        },
        {
          id: 'lSRQNw0dwdm0IDpHK9QH6',
          attributeName: 'name',
          displayName: '名称',
          attributeType: 'string',
          fgPk: false,
        },
        {
          id: 'ugQTuLJjaNNm2pMFU0bQ3',
          attributeName: 'displayName',
          displayName: '显示名称',
          attributeType: 'string',
          fgPk: false,
        },
        {
          id: 'ENem37quHAxawdY-0wPBO',
          attributeName: 'fgShow',
          displayName: '显示标志',
          attributeType: 'boolean',
          fgPk: false,
        },
        {
          id: 'ciLRtVCMsODN-H8hOatJb',
          attributeName: 'query',
          displayName: '路由参数',
          attributeType: 'string',
          fgPk: false,
        },
        {
          id: 'yqJzsGfderwil_kmuBFfI',
          attributeName: 'menuType',
          displayName: '菜单类型',
          attributeType: 'string',
          fgPk: false,
        },
        {
          id: 'rBdjPPjImQo1L8nHH5ILq',
          attributeName: 'fgActive',
          displayName: '启用标志',
          attributeType: 'boolean',
          fgPk: false,
        },
        {
          id: 'CLzF_5uwpMwz0iGFyLd02',
          attributeName: 'webPerms',
          displayName: '前端权限标识',
          attributeType: 'string',
          fgPk: false,
        },
        {
          id: 'ILWnd-SLmZzQ6g2pPFtxl',
          attributeName: 'servicePerms',
          displayName: '后台权限标识',
          attributeType: 'string',
          fgPk: false,
        },
        {
          id: 'm0amD1Ll6ZbGmvUL6YofF',
          attributeName: 'parent',
          displayName: '上级系统菜单',
          attributeType: 'TMenu',
          fgPk: false,
        },
        {
          id: '-VM5_SRQ9LLm6izagPmd2',
          attributeName: 'roleMenus',
          displayName: '系统菜单',
          attributeType: 'TRoleMenu[]',
          fgPk: false,
        },
        {
          id: 'gVRRCqIrWXU0yuZb6eq6i',
          attributeName: 'children',
          displayName: '上级系统菜单',
          attributeType: 'TMenu[]',
          fgPk: false,
        },
      ],
      fgMain: true,
      mainProperty: 'idMenu',
    },
    refTypes: [
      {
        id: '4is_YNdeqDK5cC6P4ODhm',
        className: 'TRoleMenu',
        displayName: '角色与菜单',
        attributes: [
          {
            id: 'Gf00Bnk2sy287uMBus6Qb',
            attributeName: 'idRoleMenu',
            displayName: '角色与菜单id',
            attributeType: 'string',
            fgPk: true,
          },
        ],
        fgMain: false,
        mainProperty: 'idRoleMenu',
      },
    ],
  },
  pages: [
    { key: 'index', id: 'index', code: 'index', name: '首页' },
    {
      key: 'hsk2BULOi0Ccsu_PywOWj',
      id: 'hsk2BULOi0Ccsu_PywOWj',
      code: 'edit',
      name: '编辑页',
    },
  ],
  layouts: [
    {
      key: 'root',
      id: 'root',
      title: 'root',
      idParent: null,
      order: 1,
      type: 'layout',
      direction: 'row',
      flexType: 'auto',
      flexStr: '1 1 auto',
      children: [
        {
          key: 'v_l2bb0riiNJaVtsypzW4',
          id: 'v_l2bb0riiNJaVtsypzW4',
          title: '布局1',
          idParent: 'root',
          order: 1,
          type: 'component',
          direction: 'row',
          flexType: 'custom',
          flexStr: '0 0 300px',
          children: [],
          component: {
            componentType: 'tree',
            idRef: 'RLInQtX7-sNKfYM4NMhEY',
            name: '系统菜单',
          },
          pageMaps: [
            {
              idPageMap: '69476d4a-9b4d-43ca-9e6a-ce9413f7304a',
              componentStateCode: 'list',
              pageCode: 'index',
            },
            {
              idPageMap: '36107824-c5c1-4b64-9fd2-c6634041896e',
              componentStateCode: 'form',
              pageCode: 'edit',
            },
          ],
        },
        {
          key: 'NBWOrTIk2VJPRAtdPje1j',
          id: 'NBWOrTIk2VJPRAtdPje1j',
          title: '布局2',
          idParent: 'root',
          order: 2,
          type: 'layout',
          direction: 'column',
          flexType: 'auto',
          flexStr: '1 1 auto',
          children: [
            {
              key: 'lZ6VLNjIwPx0aCk9Cxy6W',
              id: 'lZ6VLNjIwPx0aCk9Cxy6W',
              title: '布局3',
              idParent: 'NBWOrTIk2VJPRAtdPje1j',
              order: 1,
              type: 'component',
              direction: 'row',
              flexType: 'notGrow',
              flexStr: '0 1 auto',
              children: [],
              component: {
                componentType: 'editButton',
                idRef: 'pG2cu6nLmxmITlbt-so4r',
                name: '菜单编辑按钮',
              },
            },
            {
              key: 'haQYNMKC0hlnmN4ncFpa0',
              id: 'haQYNMKC0hlnmN4ncFpa0',
              title: '布局4',
              idParent: 'NBWOrTIk2VJPRAtdPje1j',
              order: 2,
              type: 'component',
              direction: 'row',
              flexType: 'auto',
              flexStr: '1 1 auto',
              children: [],
              component: {
                componentType: 'editBillform',
                idRef: 'kq6Col5Iw9c5l9jDMPy6G',
                name: '系统菜单',
              },
              pageMaps: [
                {
                  idPageMap: 'd9be75de-7ab2-4db2-878d-42a74c98defc',
                  componentStateCode: 'list',
                  pageCode: 'index',
                },
                {
                  idPageMap: '89dd8789-b237-4c24-8371-ccfb27a331ed',
                  componentStateCode: 'form',
                  pageCode: 'edit',
                },
              ],
            },
            {
              key: '1JUxo2kEtqlRHdTbRKv0Z',
              id: '1JUxo2kEtqlRHdTbRKv0Z',
              title: '布局5',
              idParent: 'NBWOrTIk2VJPRAtdPje1j',
              order: 1,
              type: 'component',
              direction: 'row',
              flexType: 'auto',
              flexStr: '1 1 auto',
              children: [],
              component: {
                componentType: 'viewBillform',
                idRef: 'kq6Col5Iw9c5l9jDMPy6G',
                name: '系统菜单',
              },
            },
          ],
        },
      ],
    },
  ],
  assos: [
    { idPage: 'index', idLayout: 'root', hidden: false, disabled: false },
    {
      idPage: 'index',
      idLayout: 'v_l2bb0riiNJaVtsypzW4',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'index',
      idLayout: 'NBWOrTIk2VJPRAtdPje1j',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'index',
      idLayout: 'lZ6VLNjIwPx0aCk9Cxy6W',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'index',
      idLayout: 'haQYNMKC0hlnmN4ncFpa0',
      hidden: false,
      disabled: true,
    },
    {
      idPage: 'hsk2BULOi0Ccsu_PywOWj',
      idLayout: 'v_l2bb0riiNJaVtsypzW4',
      hidden: false,
      disabled: true,
    },
    {
      idPage: 'hsk2BULOi0Ccsu_PywOWj',
      idLayout: 'lZ6VLNjIwPx0aCk9Cxy6W',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'hsk2BULOi0Ccsu_PywOWj',
      idLayout: 'haQYNMKC0hlnmN4ncFpa0',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'hsk2BULOi0Ccsu_PywOWj',
      idLayout: 'NBWOrTIk2VJPRAtdPje1j',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'hsk2BULOi0Ccsu_PywOWj',
      idLayout: 'root',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'index',
      idLayout: '1JUxo2kEtqlRHdTbRKv0Z',
      hidden: true,
      disabled: false,
    },
    {
      idPage: 'hsk2BULOi0Ccsu_PywOWj',
      idLayout: '1JUxo2kEtqlRHdTbRKv0Z',
      hidden: true,
      disabled: false,
    },
  ],
};

export { layoutConf };
