import { TActionContent } from '@/models';

const actionFormConf: TActionContent | undefined = {
  action: 1,
  displayName: '系统用户编辑按钮',
  idButtonAction: '0000-e17f1494-779f-46a2-9096-03598277a0f9',
  idProject: 'hLlXlmUNOcjAaDoWxZzrN',
  idSubProject: 'tuz4_94BGuVuxYxxL6a_r',
  name: 'sysuser_edit_action',
  projectName: 'Jpa基础项目',
  subProjectName: '系统模型',
  buttons: [
    {
      label: '保存',
      clickEventName: 'handleSave',
      disableScript: '',
      idButton: 'sI5tS0d7ihw9j5-YG0r1B',
      buttonSize: 'middle',
      type: 'primary',
      showOrder: 0,
      nameScript: "'保存'",
    },
    {
      label: '保存并新增',
      clickEventName: 'handleAddAgain',
      disableScript: '',
      hiddenScript: '!fgAdd',
      idButton: 'ug5xSgA8KYPlF_vQXB4hn',
      buttonSize: 'middle',
      type: 'primary',
      showOrder: 1,
      nameScript: "'保存并新增'",
    },
    {
      label: '取消',
      clickEventName: 'handleCancel',
      disableScript: '',
      idButton: 'Gs8JqPNCBIi4DGkpI2fjT',
      buttonSize: 'middle',
      type: 'primary',
      showOrder: 2,
      nameScript: "'取消'",
    },
    {
      label: '刷新',
      clickEventName: 'handleReflesh',
      disableScript: '',
      hiddenScript: '!fgAdd',
      idButton: 'HMzkOgJVcEj1a6x8oUFBn',
      buttonSize: 'middle',
      type: 'primary',
      showOrder: 3,
      nameScript: "'刷新'",
    },
  ],
  gap: '10px',
  justifyContent: 'start',
  compDisplayName: '系统用户',
  componentType: 'Single',
  idComponent: 'vUqfWDE_ELDkq0P5PjpSS',
  idComponentModule: '-IKcXCfnf_Gc2HSZEgs2v',
  componentModuleName: '系统模块',
};

export { actionFormConf };
