import { TBillFormContent } from '@/models';

const billformConf: TBillFormContent | undefined = {
  action: 1,
  billFormType: 'Combination',
  componentModuleName: '系统模块',
  componentName: '角色聚合',
  displayName: '角色聚合',
  idBillForm: 'pZZYgBwYjhcKf9_yBLdG1',
  idComponent: 'haSdru3_I3BPAFH9yI5zQ',
  idComponentModule: '-IKcXCfnf_Gc2HSZEgs2v',
  idProject: 'hLlXlmUNOcjAaDoWxZzrN',
  idSubProject: 'tuz4_94BGuVuxYxxL6a_r',
  name: 'RoleAgg',
  projectName: 'Jpa基础项目',
  subProjectName: '系统模型',
  configList: {
    idBillForm: 'vPzvJyRJLPJ1NIuC9e6qw',
    name: 'newBill',
    displayName: '新表单',
    header: [
      {
        idBillFormTab: 'mU1IWbskQ57weqYYYJ_9f',
        entityTypeName: 'Role',
        tabCode: 'role',
        firstUpperTabCode: 'Role',
        tabName: '角色',
        metadataAttrName: 'qQqrfKgHawhbjP6_BaYWm',
        tabClassName: 'Role',
        firstLowerTabClassName: 'role',
        tabAttrName: 'role',
        firstUpperTabAttrName: 'Role',
        billFormFields: [
          {
            idBillFormField: 'qGpFQIdkjbqlnhaCZ0lkC',
            name: 'idRole',
            dataType: 'PK',
            displayName: '角色id',
            fgMainProperty: true,
            showOrder: 0,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '角色id',
          },
          {
            idBillFormField: 's1tILALsZpTrDLFKnYpDZ',
            name: 'name',
            dataType: 'String',
            displayName: '名称',
            fgMainProperty: false,
            showOrder: 1,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '名称',
          },
          {
            idBillFormField: 'vrl08GIx94uNcp9WYIuMm',
            name: 'displayName',
            dataType: 'String',
            displayName: '显示名称',
            fgMainProperty: false,
            showOrder: 2,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '显示名称',
          },
        ],
        refType: 'Array',
        orderInfoList: [
          {
            idOrderInfo: 'zk3YCZrHypG3hq836O8vW',
            orderProperty: 'idRole',
            orderType: 'ASC',
          },
        ],
        fgDefaultTab: true,
        mainProperty: 'idRole',
        tabIndex: 0,
      },
    ],
    body: [
      {
        idBillFormTab: 'WKMkGxR2jHAA9lH-o_pGa',
        entityTypeName: 'RoleMenu',
        tabCode: 'roleMenus',
        firstUpperTabCode: 'RoleMenus',
        tabName: '角色菜单关系',
        metadataAttrName: '41LKU9ljL_zUTUDVWV8Fd',
        tabClassName: 'RoleMenu',
        firstLowerTabClassName: 'roleMenu',
        tabAttrName: 'roleMenus',
        firstUpperTabAttrName: 'RoleMenus',
        refType: 'Array',
        billFormFields: [
          {
            idBillFormField: 'CKUgNGT6l5Z20EmuNG0G0',
            name: 'idRoleMenu',
            dataType: 'PK',
            displayName: '角色与菜单id',
            fgMainProperty: true,
            showOrder: 0,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '角色与菜单id',
          },
          {
            idBillFormField: 'yvpAMM4FRuFNiZNcodS1f',
            name: 'idMenu',
            dataType: 'InternalRef',
            displayName: '系统菜单',
            fgMainProperty: false,
            showOrder: 1,
            refAttributeName: 'menu',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '系统菜单',
              displayProp: 'displayName',
              backWriteProp: 'idMenu',
              tableRef: {
                dataUri: '/menu/aqPage',
                tableMainProp: 'idMenu',
                idComponentEntity: '5xAwWmt5jQoncG4sUHaJs',
                ceDisplayName: '系统菜单',
                refColumns: [
                  {
                    idBillRefColumn: 'twZVxtd2IMtGnox254kWi',
                    name: 'name',
                    displayName: '名称',
                  },
                  {
                    idBillRefColumn: 'kdILN7GJmcI2yveznVWN7',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: 'uJl1KZspuEoz_TiEzBhTT',
                    name: 'fgShow',
                    displayName: '显示标志',
                  },
                  {
                    idBillRefColumn: 'E3SZiNT0in3hdImbV1EWY',
                    name: 'fgActive',
                    displayName: '启用标志',
                  },
                ],
              },
            },
            fgDisplay: true,
            width: 150,
            textLen: 140,
          },
        ],
        orderInfoList: [
          {
            idOrderInfo: 'UmmdTiKioRIHIJpOVKVXi',
            orderProperty: 'idRoleMenu',
            orderType: 'ASC',
          },
        ],
        fgDefaultTab: true,
        mainProperty: 'idRoleMenu',
        tabIndex: 0,
      },
      {
        idBillFormTab: 'J1esN8GwewjJcjwCzDuip',
        entityTypeName: 'UserRole',
        tabCode: 'userRoles',
        firstUpperTabCode: 'UserRoles',
        tabName: '用户角色关系',
        metadataAttrName: 'y7eE_qXiDmEWRTzZsHyJt',
        tabClassName: 'UserRole',
        firstLowerTabClassName: 'userRole',
        tabAttrName: 'userRoles',
        firstUpperTabAttrName: 'UserRoles',
        refType: 'Array',
        billFormFields: [
          {
            idBillFormField: 'OV7LBLNOtVZ1EwiHBXiLq',
            name: 'idUserRole',
            dataType: 'PK',
            displayName: '用户角色关系主属性',
            fgMainProperty: true,
            showOrder: 0,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '用户角色关系主属性',
          },
          {
            idBillFormField: 'DyM9yTGJZP4s174xGmg8w',
            name: 'idUser',
            dataType: 'InternalRef',
            displayName: '系统用户',
            fgMainProperty: false,
            showOrder: 1,
            refAttributeName: 'user',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '系统用户',
              displayProp: 'name',
              backWriteProp: 'idUser',
              tableRef: {
                dataUri: '/user/aqPage',
                tableMainProp: 'idUser',
                idComponentEntity: 'e8tPInbCPW7dtx-lVLOq1',
                ceDisplayName: '系统用户',
                refColumns: [
                  {
                    idBillRefColumn: 'FkWdFtiBPhgGe64Zy38Et',
                    name: 'account',
                    displayName: '登录账号 ',
                  },
                  {
                    idBillRefColumn: 'YBUR9H5_Z0JQYMhRpEU0u',
                    name: 'phone',
                    displayName: '手机号码',
                  },
                  {
                    idBillRefColumn: 'K4HqCWQ9U4avoa4aZ22mE',
                    name: 'name',
                    displayName: '姓名 ',
                  },
                  {
                    idBillRefColumn: 'wP9lxbfMYMRkJmCtw0JRU',
                    name: 'nickName',
                    displayName: '昵称',
                  },
                  {
                    idBillRefColumn: 'U6lWqPEXe7ku52InwDTFo',
                    name: 'gender',
                    displayName: '性别',
                  },
                ],
              },
            },
            fgDisplay: true,
            width: 150,
            textLen: 140,
          },
        ],
        orderInfoList: [
          {
            idOrderInfo: 'pbY1sH9gZsvqHBM3FFg9E',
            orderProperty: 'idUserRole',
            orderType: 'ASC',
          },
        ],
        fgDefaultTab: false,
        mainProperty: 'idUserRole',
        tabIndex: 1,
      },
    ],
    tail: [],
    mainClass: 'Role',
    mainProperty: 'idRole',
    uriConf: {
      page: '/roleAgg/aqPage',
      fetchById: '/roleAgg/getById',
      batchRemove: '/roleAgg/batchRemove',
    },
  },
  configForm: {
    idBillForm: 'vPzvJyRJLPJ1NIuC9e6qw',
    name: 'newBill',
    displayName: '新表单',
    header: [
      {
        idBillFormTab: 'mU1IWbskQ57weqYYYJ_9f',
        entityTypeName: 'Role',
        tabCode: 'role',
        firstUpperTabCode: 'Role',
        tabName: '角色',
        metadataAttrName: 'qQqrfKgHawhbjP6_BaYWm',
        tabClassName: 'Role',
        firstLowerTabClassName: 'role',
        tabAttrName: 'role',
        firstUpperTabAttrName: 'Role',
        billFormFields: [
          {
            idBillFormField: 'qGpFQIdkjbqlnhaCZ0lkC',
            name: 'idRole',
            dataType: 'PK',
            displayName: '角色id',
            fgMainProperty: true,
            showOrder: 0,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '角色id',
          },
          {
            idBillFormField: 's1tILALsZpTrDLFKnYpDZ',
            name: 'name',
            dataType: 'String',
            displayName: '名称',
            fgMainProperty: false,
            showOrder: 1,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '名称',
          },
          {
            idBillFormField: 'vrl08GIx94uNcp9WYIuMm',
            name: 'displayName',
            dataType: 'String',
            displayName: '显示名称',
            fgMainProperty: false,
            showOrder: 2,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '显示名称',
          },
        ],
        refType: 'Array',
        orderInfoList: [
          {
            idOrderInfo: 'zk3YCZrHypG3hq836O8vW',
            orderProperty: 'idRole',
            orderType: 'ASC',
          },
        ],
        fgDefaultTab: true,
        mainProperty: 'idRole',
        tabIndex: 0,
      },
    ],
    body: [
      {
        idBillFormTab: 'WKMkGxR2jHAA9lH-o_pGa',
        entityTypeName: 'RoleMenu',
        tabCode: 'roleMenus',
        firstUpperTabCode: 'RoleMenus',
        tabName: '角色菜单关系',
        metadataAttrName: '41LKU9ljL_zUTUDVWV8Fd',
        tabClassName: 'RoleMenu',
        firstLowerTabClassName: 'roleMenu',
        tabAttrName: 'roleMenus',
        firstUpperTabAttrName: 'RoleMenus',
        refType: 'Array',
        billFormFields: [
          {
            idBillFormField: 'CKUgNGT6l5Z20EmuNG0G0',
            name: 'idRoleMenu',
            dataType: 'PK',
            displayName: '角色与菜单id',
            fgMainProperty: true,
            showOrder: 0,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '角色与菜单id',
          },
          {
            idBillFormField: 'yvpAMM4FRuFNiZNcodS1f',
            name: 'idMenu',
            dataType: 'InternalRef',
            displayName: '系统菜单',
            fgMainProperty: false,
            showOrder: 1,
            refAttributeName: 'menu',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '系统菜单',
              displayProp: 'displayName',
              backWriteProp: 'idMenu',
              tableRef: {
                dataUri: '/menu/aqPage',
                tableMainProp: 'idMenu',
                idComponentEntity: '5xAwWmt5jQoncG4sUHaJs',
                ceDisplayName: '系统菜单',
                refColumns: [
                  {
                    idBillRefColumn: 'twZVxtd2IMtGnox254kWi',
                    name: 'name',
                    displayName: '名称',
                  },
                  {
                    idBillRefColumn: 'kdILN7GJmcI2yveznVWN7',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: 'uJl1KZspuEoz_TiEzBhTT',
                    name: 'fgShow',
                    displayName: '显示标志',
                  },
                  {
                    idBillRefColumn: 'E3SZiNT0in3hdImbV1EWY',
                    name: 'fgActive',
                    displayName: '启用标志',
                  },
                ],
              },
            },
            fgDisplay: true,
            width: 150,
            textLen: 140,
          },
        ],
        orderInfoList: [
          {
            idOrderInfo: 'UmmdTiKioRIHIJpOVKVXi',
            orderProperty: 'idRoleMenu',
            orderType: 'ASC',
          },
        ],
        fgDefaultTab: true,
        mainProperty: 'idRoleMenu',
        tabIndex: 0,
      },
      {
        idBillFormTab: 'J1esN8GwewjJcjwCzDuip',
        entityTypeName: 'UserRole',
        tabCode: 'userRoles',
        firstUpperTabCode: 'UserRoles',
        tabName: '用户角色关系',
        metadataAttrName: 'y7eE_qXiDmEWRTzZsHyJt',
        tabClassName: 'UserRole',
        firstLowerTabClassName: 'userRole',
        tabAttrName: 'userRoles',
        firstUpperTabAttrName: 'UserRoles',
        refType: 'Array',
        billFormFields: [
          {
            idBillFormField: 'OV7LBLNOtVZ1EwiHBXiLq',
            name: 'idUserRole',
            dataType: 'PK',
            displayName: '用户角色关系主属性',
            fgMainProperty: true,
            showOrder: 0,
            fgTreeAttr: false,
            fgDisplay: true,
            readonly: false,
            inputType: 'Input',
            typeScriptType: 'string',
            width: 150,
            textLen: 140,
            placeholder: '用户角色关系主属性',
          },
          {
            idBillFormField: 'DyM9yTGJZP4s174xGmg8w',
            name: 'idUser',
            dataType: 'InternalRef',
            displayName: '系统用户',
            fgMainProperty: false,
            showOrder: 1,
            refAttributeName: 'user',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '系统用户',
              displayProp: 'name',
              backWriteProp: 'idUser',
              tableRef: {
                dataUri: '/user/aqPage',
                tableMainProp: 'idUser',
                idComponentEntity: 'e8tPInbCPW7dtx-lVLOq1',
                ceDisplayName: '系统用户',
                refColumns: [
                  {
                    idBillRefColumn: 'FkWdFtiBPhgGe64Zy38Et',
                    name: 'account',
                    displayName: '登录账号 ',
                  },
                  {
                    idBillRefColumn: 'YBUR9H5_Z0JQYMhRpEU0u',
                    name: 'phone',
                    displayName: '手机号码',
                  },
                  {
                    idBillRefColumn: 'K4HqCWQ9U4avoa4aZ22mE',
                    name: 'name',
                    displayName: '姓名 ',
                  },
                  {
                    idBillRefColumn: 'wP9lxbfMYMRkJmCtw0JRU',
                    name: 'nickName',
                    displayName: '昵称',
                  },
                  {
                    idBillRefColumn: 'U6lWqPEXe7ku52InwDTFo',
                    name: 'gender',
                    displayName: '性别',
                  },
                ],
              },
            },
            fgDisplay: true,
            width: 150,
            textLen: 140,
          },
        ],
        orderInfoList: [
          {
            idOrderInfo: 'pbY1sH9gZsvqHBM3FFg9E',
            orderProperty: 'idUserRole',
            orderType: 'ASC',
          },
        ],
        fgDefaultTab: false,
        mainProperty: 'idUserRole',
        tabIndex: 1,
      },
    ],
    tail: [],
    mainClass: 'Role',
    mainProperty: 'idRole',
    uriConf: {
      fetchById: '/roleAgg/getById',
      save: '/roleAgg/save',
      update: '/roleAgg/save',
      dataRemove: '/roleAgg/remove',
    },
  },
};

export { billformConf };
